---

- name: configure sysctl
  block:
    - name: sysctl vm.overcommit_memory
      sysctl:
        name: vm.overcommit_memory
        value: '1'
        state: present
    - name: sysctl net.ipv4.tcp_max_tw_buckets
      sysctl:
        name: net.ipv4.tcp_max_tw_buckets
        value: '2000000'
        state: present
    - name: sysctl net.ipv4.ip_local_port_range
      sysctl:
        name: net.ipv4.ip_local_port_range
        value: '10000 65000'
        state: present
    - name: sysctl net.core.somaxconn
      sysctl:
        name: net.core.somaxconn
        value: '32768'
        state: present
    - name: sysctl net.core.netdev_max_backlog
      sysctl:
        name: net.core.netdev_max_backlog
        value: '8192'
        state: present
    - name: sysctl net.ipv4.tcp_tw_reuse
      sysctl:
        name: net.ipv4.tcp_tw_reuse
        value: '1'
        state: present
    - name: sysctl net.ipv4.tcp_fin_timeout
      sysctl:
        name: net.ipv4.tcp_fin_timeout
        value: '8192'
        state: present
        reload: yes # 最後にかならず

- name: touch /etc/rc.local
  file:
    path: /etc/rc.local
    state: touch
    mode: '0755'

- name: disable kernel.mm.transparent_hugepage
  lineinfile:
    dest: /etc/rc.local
    line: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    insertbefore: "exit 0"

- name: set never for kernel.mm.transparent_hugepage
  shell: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
