---

- name: copy plugin config
  copy: src=config/netdata/{{ item }} dest=/etc/netdata/python.d/{{ item }} owner=netdata group=netdata mode=0644
  with_items:
    - nginx.conf
    - web_log.conf

- name: restart netdata
  systemd:
    state: restarted
    name: netdata
