---

- hosts: all
  become: yes
  tasks:
    - include: tasks/01_common.yaml
    - include: tasks/02_apt.yaml # XXX: tags:mysqlのタスクはこのaptの設定変更に依存しているので注意
    - include: tasks/03_packages.yaml
    - include: tasks/04_tools.yaml
    - include: tasks/05_netdata.yaml
    # - include: tasks/06_kernel.yaml # TODO: 悪化することもあるので状況に応じて/バックアップを取ってから
  tags: init
  vars:
    install_mysql_libs: no
    use_community_mysql: &use_community_mysql no
    mysql_version: &mysql_version 8.0
    mysql_uninstall: &mysql_uninstall no # アップグレードの際はyesにする

- hosts: all
  become: yes
  tasks:
    - include: tasks/05_netdata.yaml
  tags: netdata

- hosts: all
  become: yes
  tasks:
    - include: tasks/06_kernel.yaml
  tags: kernel

- hosts: proxy
  become: yes
  tasks:
    - include: tasks/nginx/01_install.yaml
    - include: tasks/nginx/02_configuration.yaml
    - include: tasks/nginx/03_netdata.yaml
  tags: nginx

- hosts: db
  become: yes
  tasks:
    - include: tasks/mysql/01_install.yaml
    - include: tasks/mysql/02_configuration.yaml
    - include: tasks/mysql/03_netdata.yaml
  tags: mysql
  vars:
    use_community_mysql: *use_community_mysql
    mysql_version: *mysql_version
    mysql_uninstall: *mysql_uninstall

- hosts: redis
  become: yes
  tasks:
    - include: tasks/redis/01_install.yaml
    - include: tasks/redis/02_configuration.yaml
    - include: tasks/redis/03_netdata.yaml
  tags: redis
